list_key_ko:
  - ["ㅂ", "ㅈ", "ㄷ", "ㄱ", "ㅅ", "ㅛ", "ㅕ", "ㅑ", "ㅐ", "ㅔ"]
  - ["ㅁ", "ㄴ", "ㅇ", "ㄹ", "ㅎ", "ㅗ", "ㅓ", "ㅏ", "ㅣ"]
  - ["ㅋ", "ㅌ", "ㅊ", "ㅍ", "ㅠ", "ㅜ", "ㅡ"]

list_key_en_upper:
    - ["Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P"]
    - ["A", "S", "D", "F", "G", "H", "J", "K", "L"]
    - ["Z", "X", "C", "V", "B", "N", "M"]

list_key_en_lower:
  - ["q", "w", "e", "r", "t", "y", "u", "i", "o", "p"]
  - ["a", "s", "d", "f", "g", "h", "j", "k", "l"]
  - ["z", "x", "c", "v", "b", "n", "m"]

list_ja:
  - "ㄱ"
  - "ㄴ"
  - "ㄷ"
  - "ㄹ"
  - "ㅁ"
  - "ㅂ"
  - "ㅅ"
  - "ㅇ"
  - "ㅈ"
  - "ㅊ"
  - "ㅋ"
  - "ㅌ"
  - "ㅍ"
  - "ㅎ"

list_mo:
  - "ㅏ"
  - "ㅑ"
  - "ㅓ"
  - "ㅕ"
  - "ㅗ"
  - "ㅓ"
  - "ㅜ"
  - "ㅠ"
  - "ㅡ"
  - "ㅣ"

dict_symbol:
  "!": "1"
  "@": "2"
  "#": "3"
  "$": "4"
  "%": "5"
  "^": "6"
  "&": "7"
  "*": "8"
  "(": "9"
  ")": "0"
  "[": "{"
  "{": "["
  "]": "}"
  "}": "]"
  ":": ";"
  ";": ":"
  ",": "."
  ".": ","
  "/": "?"
  "?": "/"
  "-": "_"
  "_": "-"

dict_shift_on:
  "ㅂ": "ㅃ"
  "ㅈ": "ㅉ"
  "ㄷ": "ㄸ"
  "ㄱ": "ㄲ"
  "ㅅ": "ㅆ"
  "ㅐ": "ㅒ"
  "ㅔ": "ㅖ"

dict_shift_off:
  "ㅃ": "ㅂ"
  "ㅉ": "ㅈ"
  "ㄸ": "ㄷ"
  "ㄲ": "ㄱ"
  "ㅆ": "ㅅ"
  "ㅒ": "ㅐ"
  "ㅖ": "ㅔ"

dict_diphthong:
  "ㅘ": ["ㅙ", "ㅚ"]
  "ㅙ": ["ㅘ", "ㅚ"]
  "ㅚ": ["ㅘ", "ㅙ"]
  "ㅝ": ["ㅞ", "ㅟ"]
  "ㅞ": ["ㅝ", "ㅟ"]
  "ㅟ": ["ㅝ", "ㅞ"]
  "ㅢ": ["ㅚ", "ㅟ"]